In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd '/content/drive/MyDrive/DATA'

/content/drive/MyDrive/DATA

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data = []

for page in range(1, 201):
    url = f"https://finance.naver.com/item/news.naver?code=005930&page={page}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    iframe = soup.find("iframe", {"id": "news_frame"})
    iframe_src = iframe["src"]

    iframe_response = requests.get("https://finance.naver.com" + iframe_src)
    iframe_soup = BeautifulSoup(iframe_response.text, "html.parser")

    table = iframe_soup.find("table", class_="type5")
    rows = table.find_all("tr")

    for row in rows:
        title = row.find("td", class_="title")
        if title is not None:
            title_text = title.text.strip()
            info = row.find("td", class_="info")
            date = row.find("td", class_="date")
            info_text = info.text.strip() if info is not None else ""
            date_text = date.text.strip() if date is not None else ""
            data.append({"Page": page, "Title": title_text, "Info": info_text, "Date": date_text})

df = pd.DataFrame(data)
df.to_csv("output.csv", index=False)

In [ ]:
file_path = 'output.csv'
data = pd.read_csv(file_path)
data

,Page,Title,Info,Date
0,1,'인류 공헌이 기업 사명' KH 유산 받은 이재용…삼성 사회공헌 박차,아시아경제,2023.06.05 14:39
1,1,"한종희 삼성 부회장 ""지속가능한 가전제품, 삼성이 유리""",뉴시스,2023.06.05 14:34
2,1,"한종희 삼성 부회장 ""'비스포크 라이프'서 맞춤형 가전 솔루션 제시""",아시아경제,2023.06.05 08:55
3,1,"한종희 삼성 부회장 ""'비스포크 라이프'서 맞춤형 가전 솔루션 제시""",아시아경제,2023.06.05 08:55
4,1,친환경도 앞장서는 삼성… 수원사업장에 ESG 라운지 오픈,서울경제,2023.06.05 14:30
...,...,...,...,...
5862,200,“실물 결국 유출됐네” 난리난 삼성 제품 ‘이렇게’ 생겼다,헤럴드경제,2023.04.30 22:00
5863,200,오포·화웨이 中 폴더블 시장 점령.. 삼성 '갤Z 시리즈' 조기에 내...,파이낸셜뉴스,2023.04.30 18:24
5864,200,오포·화웨이 中 폴더블 시장 점령.. 삼성 '갤Z 시리즈' 조기에 내...,파이낸셜뉴스,2023.04.30 18:24
5865,200,中 폴더블폰시장 오포도 삼성제쳐.. 갤럭시Z 조기 출격하나,파이낸셜뉴스,2023.04.30 15:08
5866,200,삼성 '갓성비' 태블릿 보강…50만원대 갤탭 출격,서울경제,2023.04.30 18:11